<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 26,
                'name' => 'ARTICULOS DE FERRETERIA',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 26,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006452,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'VIVERES II',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005956,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            2 => 
            array (
                'id' => 1,
                'name' => 'PANES Y TORTAS',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005394,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            3 => 
            array (
                'id' => 3,
                'name' => 'CUIDADO PERSONAL',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005609,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            4 => 
            array (
                'id' => 4,
                'name' => 'REPOSTERIA',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006078,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            5 => 
            array (
                'id' => 5,
                'name' => 'QUESOS PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005264,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            6 => 
            array (
                'id' => 6,
                'name' => 'VEGETALES PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005257,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            7 => 
            array (
                'id' => 7,
                'name' => 'CESTA BASICA II',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005879,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            8 => 
            array (
                'id' => 8,
                'name' => 'CHARCUTERIA NO PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005549,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            9 => 
            array (
                'id' => 9,
                'name' => 'INFANTIL/CEREAL/GALLETAS',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006031,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            10 => 
            array (
                'id' => 10,
                'name' => 'CESTA BASICA I',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005568,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            11 => 
            array (
                'id' => 11,
                'name' => 'ASEO HOGAR',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005750,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            12 => 
            array (
                'id' => 12,
                'name' => 'JUGUETERIA',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006311,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            13 => 
            array (
                'id' => 13,
                'name' => 'VIVERES I',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 13,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005923,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            14 => 
            array (
                'id' => 14,
                'name' => 'CHARCUTERIA PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005517,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            15 => 
            array (
                'id' => 15,
                'name' => 'MASCOTAS',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005847,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            16 => 
            array (
                'id' => 16,
                'name' => 'BEBIDAS Y PASAPALOS',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 16,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006129,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            17 => 
            array (
                'id' => 17,
                'name' => 'FRUTAS PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005428,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            18 => 
            array (
                'id' => 18,
                'name' => 'COMIDAS CONGELADAS NO PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 18,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005483,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            19 => 
            array (
                'id' => 19,
                'name' => 'LACTEOS JUGOS Y DERIVADOS',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 19,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005335,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            20 => 
            array (
                'id' => 20,
                'name' => 'CARNES FRESCAS PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 20,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005456,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            21 => 
            array (
                'id' => 21,
                'name' => 'QUESOS NO PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 21,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005315,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            22 => 
            array (
                'id' => 22,
                'name' => 'LICORES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 22,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006169,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            23 => 
            array (
                'id' => 23,
                'name' => 'CAMPING Y DEPORTE',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 23,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006263,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            24 => 
            array (
                'id' => 24,
                'name' => 'AVES CONGELADAS PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 24,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005471,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
            25 => 
            array (
                'id' => 25,
                'name' => 'VEGETALES NO PESABLES',
                'description' => NULL,
                'image' => NULL,
                'parent_id' => NULL,
                'order' => 25,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005419,
                'created_at' => NULL,
                'updated_at' => '2020-04-14 13:39:47',
                'adulto' => 'N',
            ),
        ));
        
        
    }
}