<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 22,
                'name' => 'LICORES',
                'description' => NULL,
                'image' => 'categories\\April2020\\oU9wjlwIrYbcv2yrjE54.png',
                'parent_id' => NULL,
                'order' => 22,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006169,
                'created_at' => NULL,
                'updated_at' => '2020-04-16 00:55:14',
                'adulto' => 'Y',
            ),
            1 => 
            array (
                'id' => 26,
                'name' => 'ARTICULOS DE FERRETERIA',
                'description' => NULL,
                'image' => 'categories\\April2020\\zI1EFTpwFkucl7bEThFw.png',
                'parent_id' => NULL,
                'order' => 26,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006452,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:10:50',
                'adulto' => 'N',
            ),
            2 => 
            array (
                'id' => 11,
                'name' => 'ASEO HOGAR',
                'description' => NULL,
                'image' => 'categories\\April2020\\3Dqm4ulBY3PIjzF0N6ZB.png',
                'parent_id' => NULL,
                'order' => 11,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005750,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:10:58',
                'adulto' => 'N',
            ),
            3 => 
            array (
                'id' => 24,
                'name' => 'AVES CONGELADAS PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\oKtueIb1Oo1ztEZqkllE.png',
                'parent_id' => NULL,
                'order' => 24,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005471,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:11:37',
                'adulto' => 'N',
            ),
            4 => 
            array (
                'id' => 16,
                'name' => 'BEBIDAS Y PASAPALOS',
                'description' => NULL,
                'image' => 'categories\\April2020\\dihSPzkHWG1b2eZJeyYi.png',
                'parent_id' => NULL,
                'order' => 16,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006129,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:11:48',
                'adulto' => 'N',
            ),
            5 => 
            array (
                'id' => 23,
                'name' => 'CAMPING Y DEPORTE',
                'description' => NULL,
                'image' => 'categories\\April2020\\uIUXeMT8un9WmyigtVka.png',
                'parent_id' => NULL,
                'order' => 23,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006263,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:12:08',
                'adulto' => 'N',
            ),
            6 => 
            array (
                'id' => 20,
                'name' => 'CARNES FRESCAS PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\OIwjsycOV77bkMW1ecYS.png',
                'parent_id' => NULL,
                'order' => 20,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005456,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:12:41',
                'adulto' => 'N',
            ),
            7 => 
            array (
                'id' => 10,
                'name' => 'CESTA BASICA I',
                'description' => NULL,
                'image' => 'categories\\April2020\\4qA1M8Je6FU2dyucPW8i.png',
                'parent_id' => NULL,
                'order' => 10,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005568,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:12:50',
                'adulto' => 'N',
            ),
            8 => 
            array (
                'id' => 18,
                'name' => 'COMIDAS CONGELADAS NO PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\SLVIqvccCMBW1pucT5Ek.png',
                'parent_id' => NULL,
                'order' => 18,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005483,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:13:09',
                'adulto' => 'N',
            ),
            9 => 
            array (
                'id' => 15,
                'name' => 'MASCOTAS',
                'description' => NULL,
                'image' => 'categories\\April2020\\LrL7e07DzoekWpSmi2j3.png',
                'parent_id' => NULL,
                'order' => 15,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005847,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:13:30',
                'adulto' => 'N',
            ),
            10 => 
            array (
                'id' => 2,
                'name' => 'VIVERES II',
                'description' => NULL,
                'image' => 'categories\\April2020\\U9oZteLTsXKRqeqpTYS2.png',
                'parent_id' => NULL,
                'order' => 1,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005956,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:13:38',
                'adulto' => 'N',
            ),
            11 => 
            array (
                'id' => 8,
                'name' => 'CHARCUTERIA NO PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\qol3DK4IBfVa331UWSOa.png',
                'parent_id' => NULL,
                'order' => 8,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005549,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:13:45',
                'adulto' => 'N',
            ),
            12 => 
            array (
                'id' => 4,
                'name' => 'REPOSTERIA',
                'description' => NULL,
                'image' => 'categories\\April2020\\SC0cTcRbZ6gBjbHrqxKt.png',
                'parent_id' => NULL,
                'order' => 4,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006078,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:13:54',
                'adulto' => 'N',
            ),
            13 => 
            array (
                'id' => 5,
                'name' => 'QUESOS PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\9XH9Ov9uwVkExgqaCzx9.png',
                'parent_id' => NULL,
                'order' => 5,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005264,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:14:01',
                'adulto' => 'N',
            ),
            14 => 
            array (
                'id' => 7,
                'name' => 'CESTA BASICA II',
                'description' => NULL,
                'image' => 'categories\\April2020\\0VNV7XG3LSM858sOTNCu.png',
                'parent_id' => NULL,
                'order' => 7,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005879,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:14:31',
                'adulto' => 'N',
            ),
            15 => 
            array (
                'id' => 3,
                'name' => 'CUIDADO PERSONAL',
                'description' => NULL,
                'image' => 'categories\\April2020\\fUZa7NoDObRnKgGKmJ8D.png',
                'parent_id' => NULL,
                'order' => 3,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005609,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:14:41',
                'adulto' => 'N',
            ),
            16 => 
            array (
                'id' => 9,
                'name' => 'INFANTIL/CEREAL/GALLETAS',
                'description' => NULL,
                'image' => 'categories\\April2020\\o1twvNv8ddhN7OWOYNgg.png',
                'parent_id' => NULL,
                'order' => 9,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006031,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:14:49',
                'adulto' => 'N',
            ),
            17 => 
            array (
                'id' => 12,
                'name' => 'JUGUETERIA',
                'description' => NULL,
                'image' => 'categories\\April2020\\QZML8O6rXDJY2poJZEx8.png',
                'parent_id' => NULL,
                'order' => 12,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1006311,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:14:57',
                'adulto' => 'N',
            ),
            18 => 
            array (
                'id' => 1,
                'name' => 'PANES Y TORTAS',
                'description' => NULL,
                'image' => 'categories\\April2020\\F6musZDhuJHUrYZizLEo.png',
                'parent_id' => NULL,
                'order' => 2,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005394,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:15:41',
                'adulto' => 'N',
            ),
            19 => 
            array (
                'id' => 14,
                'name' => 'CHARCUTERIA PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\iiyoFJ1yEANjy7MCVq1q.png',
                'parent_id' => NULL,
                'order' => 14,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005517,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:15:49',
                'adulto' => 'N',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'QUESOS NO PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\hSPi5NKjOmJfDhLhOxQO.png',
                'parent_id' => NULL,
                'order' => 21,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005315,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:15:57',
                'adulto' => 'N',
            ),
            21 => 
            array (
                'id' => 17,
                'name' => 'FRUTAS PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\2LTegV89l9xTx6XUPPH5.png',
                'parent_id' => NULL,
                'order' => 17,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005428,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:16:06',
                'adulto' => 'N',
            ),
            22 => 
            array (
                'id' => 13,
                'name' => 'VIVERES I',
                'description' => NULL,
                'image' => 'categories\\April2020\\ISprLAIqAFvWifK6TihM.png',
                'parent_id' => NULL,
                'order' => 13,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005923,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:16:15',
                'adulto' => 'N',
            ),
            23 => 
            array (
                'id' => 6,
                'name' => 'VEGETALES PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\VgIaC3LWYKV4Q5vbQEs9.png',
                'parent_id' => NULL,
                'order' => 6,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005257,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:16:24',
                'adulto' => 'N',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'VEGETALES NO PESABLES',
                'description' => NULL,
                'image' => 'categories\\April2020\\XrACoiTiqliOBNmNbMBv.png',
                'parent_id' => NULL,
                'order' => 25,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005419,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:16:32',
                'adulto' => 'N',
            ),
            25 => 
            array (
                'id' => 19,
                'name' => 'LACTEOS JUGOS Y DERIVADOS',
                'description' => NULL,
                'image' => 'categories\\April2020\\mVUWdErmA0iEsB76PWkp.png',
                'parent_id' => NULL,
                'order' => 19,
                'slug' => NULL,
                'status' => 'A',
                'c_elementvalue_id_n3' => 1005335,
                'created_at' => NULL,
                'updated_at' => '2020-04-17 23:16:42',
                'adulto' => 'N',
            ),
        ));
        
        
    }
}