<?php

use Illuminate\Database\Seeder;

class DetBankOrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('det_bank_orders')->delete();
        
        \DB::table('det_bank_orders')->insert(array (
            0 => 
            array (
                'id' => 2,
                'amount' => '121000.00',
                'orders_id' => 1,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'dfgh',
                'image' => NULL,
                'created_at' => '2020-04-16 18:32:23',
                'updated_at' => '2020-04-16 18:32:23',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'amount' => '1100.00',
                'orders_id' => 1,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'klkl',
                'image' => NULL,
                'created_at' => '2020-04-16 18:32:37',
                'updated_at' => '2020-04-16 18:32:37',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'amount' => '229900.00',
                'orders_id' => 3,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'ghj',
                'image' => NULL,
                'created_at' => '2020-04-16 18:33:16',
                'updated_at' => '2020-04-16 18:33:16',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'amount' => '0.00',
                'orders_id' => 3,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'sdfg',
                'image' => NULL,
                'created_at' => '2020-04-16 19:31:32',
                'updated_at' => '2020-04-16 19:31:32',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'amount' => '0.00',
                'orders_id' => 3,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'sdfg',
                'image' => NULL,
                'created_at' => '2020-04-16 19:32:58',
                'updated_at' => '2020-04-16 19:32:58',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'amount' => '0.00',
                'orders_id' => 3,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'sdfg',
                'image' => NULL,
                'created_at' => '2020-04-16 19:34:37',
                'updated_at' => '2020-04-16 19:34:37',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'amount' => '0.00',
                'orders_id' => 3,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'fdgh',
                'image' => NULL,
                'created_at' => '2020-04-16 19:36:22',
                'updated_at' => '2020-04-16 19:36:22',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'amount' => '203500.00',
                'orders_id' => 4,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'uuy',
                'image' => NULL,
                'created_at' => '2020-04-16 20:09:46',
                'updated_at' => '2020-04-16 20:09:46',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            8 => 
            array (
                'id' => 12,
                'amount' => '1100.00',
                'orders_id' => 4,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'huj',
                'image' => NULL,
                'created_at' => '2020-04-16 20:09:56',
                'updated_at' => '2020-04-16 20:09:56',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'amount' => '113300.00',
                'orders_id' => 5,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'sdfg',
                'image' => NULL,
                'created_at' => '2020-04-16 20:12:29',
                'updated_at' => '2020-04-16 20:12:29',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'amount' => '236500.00',
                'orders_id' => 7,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'yui',
                'image' => NULL,
                'created_at' => '2020-04-16 20:17:08',
                'updated_at' => '2020-04-16 20:17:08',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            11 => 
            array (
                'id' => 15,
                'amount' => '1632400.00',
                'orders_id' => 8,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'fghj',
                'image' => NULL,
                'created_at' => '2020-04-16 20:17:31',
                'updated_at' => '2020-04-16 20:17:31',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'amount' => '460437.71',
                'orders_id' => 9,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'fgh',
                'image' => NULL,
                'created_at' => '2020-04-16 20:18:34',
                'updated_at' => '2020-04-16 20:18:34',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            13 => 
            array (
                'id' => 17,
                'amount' => '0.01',
                'orders_id' => 9,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'gfjghj',
                'image' => NULL,
                'created_at' => '2020-04-16 20:18:43',
                'updated_at' => '2020-04-16 20:18:43',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            14 => 
            array (
                'id' => 1,
                'amount' => '2829200.00',
                'orders_id' => 2,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'jj',
                'image' => NULL,
                'created_at' => '2020-04-16 18:19:26',
                'updated_at' => '2020-04-17 00:30:40',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'amount' => '220000.00',
                'orders_id' => 10,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 09:52:09',
                'updated_at' => '2020-04-17 09:52:09',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            16 => 
            array (
                'id' => 19,
                'amount' => '12100.00',
                'orders_id' => 10,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 09:52:47',
                'updated_at' => '2020-04-17 09:52:47',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            17 => 
            array (
                'id' => 20,
                'amount' => '1100.00',
                'orders_id' => 10,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 09:53:12',
                'updated_at' => '2020-04-17 09:53:12',
                'other_amount' => NULL,
                'coins_id' => NULL,
                'description' => NULL,
            ),
            18 => 
            array (
                'id' => 21,
                'amount' => '248600.00',
                'orders_id' => 11,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 10:11:58',
                'updated_at' => '2020-04-17 10:11:58',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            19 => 
            array (
                'id' => 22,
                'amount' => '1100.00',
                'orders_id' => 11,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 10:15:11',
                'updated_at' => '2020-04-17 10:15:11',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            20 => 
            array (
                'id' => 23,
                'amount' => '17600.00',
                'orders_id' => 12,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 10:17:01',
                'updated_at' => '2020-04-17 10:17:01',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            21 => 
            array (
                'id' => 24,
                'amount' => '35200.00',
                'orders_id' => 13,
                'bank_datas_id' => 2,
                'status' => 'nuevo',
                'ref' => 'null',
                'image' => NULL,
                'created_at' => '2020-04-17 10:23:22',
                'updated_at' => '2020-04-17 10:23:22',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            22 => 
            array (
                'id' => 25,
                'amount' => '1100.00',
                'orders_id' => 13,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 10:24:59',
                'updated_at' => '2020-04-17 10:24:59',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            23 => 
            array (
                'id' => 26,
                'amount' => '319000.00',
                'orders_id' => 14,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 10:41:08',
                'updated_at' => '2020-04-17 10:41:08',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            24 => 
            array (
                'id' => 27,
                'amount' => '300000.00',
                'orders_id' => 15,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'ghjgh',
                'image' => NULL,
                'created_at' => '2020-04-17 10:42:40',
                'updated_at' => '2020-04-17 10:42:40',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            25 => 
            array (
                'id' => 28,
                'amount' => '33000.00',
                'orders_id' => 15,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 10:43:21',
                'updated_at' => '2020-04-17 10:43:21',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            26 => 
            array (
                'id' => 29,
                'amount' => '11000.00',
                'orders_id' => 15,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 10:43:53',
                'updated_at' => '2020-04-17 10:43:53',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            27 => 
            array (
                'id' => 30,
                'amount' => '483420.00',
                'orders_id' => 16,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'jj',
                'image' => NULL,
                'created_at' => '2020-04-17 10:45:06',
                'updated_at' => '2020-04-17 10:45:06',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            28 => 
            array (
                'id' => 31,
                'amount' => '8.58',
                'orders_id' => 16,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'ghjgh',
                'image' => NULL,
                'created_at' => '2020-04-17 10:50:02',
                'updated_at' => '2020-04-17 10:50:02',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'amount' => '175600.00',
                'orders_id' => 17,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'hjk',
                'image' => NULL,
                'created_at' => '2020-04-17 10:52:25',
                'updated_at' => '2020-04-17 10:52:25',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'amount' => '57.00',
                'orders_id' => 17,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'fdgh',
                'image' => NULL,
                'created_at' => '2020-04-17 10:55:18',
                'updated_at' => '2020-04-17 10:55:18',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            31 => 
            array (
                'id' => 34,
                'amount' => '0.14',
                'orders_id' => 17,
                'bank_datas_id' => 1,
                'status' => 'nuevo',
                'ref' => 'gfhfg',
                'image' => NULL,
                'created_at' => '2020-04-17 10:55:26',
                'updated_at' => '2020-04-17 10:55:26',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            32 => 
            array (
                'id' => 47,
                'amount' => '766200.45',
                'orders_id' => 26,
                'bank_datas_id' => 1,
                'status' => 'rechazado',
                'ref' => 'hghg',
                'image' => NULL,
                'created_at' => '2020-04-17 14:14:18',
                'updated_at' => '2020-04-17 18:30:32',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            33 => 
            array (
                'id' => 48,
                'amount' => '766200.45',
                'orders_id' => 26,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'hjjh',
                'image' => NULL,
                'created_at' => '2020-04-17 14:33:31',
                'updated_at' => '2020-04-17 18:33:43',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            34 => 
            array (
                'id' => 49,
                'amount' => '165000.00',
                'orders_id' => 27,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 14:51:15',
                'updated_at' => '2020-04-17 14:51:15',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            35 => 
            array (
                'id' => 35,
                'amount' => '478246.32',
                'orders_id' => 18,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'GGGGGGGG',
                'image' => NULL,
                'created_at' => '2020-04-17 11:43:15',
                'updated_at' => '2020-04-17 16:00:35',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            36 => 
            array (
                'id' => 36,
                'amount' => '234586.80',
                'orders_id' => 19,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'vv',
                'image' => NULL,
                'created_at' => '2020-04-17 11:55:17',
                'updated_at' => '2020-04-17 16:03:20',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            37 => 
            array (
                'id' => 37,
                'amount' => '200000.00',
                'orders_id' => 20,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'HHH',
                'image' => NULL,
                'created_at' => '2020-04-17 12:04:28',
                'updated_at' => '2020-04-17 16:04:54',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            38 => 
            array (
                'id' => 38,
                'amount' => '215714.29',
                'orders_id' => 20,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'JJJ',
                'image' => NULL,
                'created_at' => '2020-04-17 12:04:39',
                'updated_at' => '2020-04-17 16:23:37',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            39 => 
            array (
                'id' => 39,
                'amount' => '307889.98',
                'orders_id' => 21,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'HJHJJ',
                'image' => NULL,
                'created_at' => '2020-04-17 12:24:44',
                'updated_at' => '2020-04-17 16:25:03',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            40 => 
            array (
                'id' => 40,
                'amount' => '400400.00',
                'orders_id' => 22,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 12:25:45',
                'updated_at' => '2020-04-17 12:25:45',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'amount' => '34100.00',
                'orders_id' => 23,
                'bank_datas_id' => 2,
                'status' => 'efectivo',
                'ref' => 'EFECTIVO',
                'image' => NULL,
                'created_at' => '2020-04-17 12:27:23',
                'updated_at' => '2020-04-17 12:27:23',
                'other_amount' => '1100.00',
                'coins_id' => 1,
                'description' => NULL,
            ),
            42 => 
            array (
                'id' => 41,
                'amount' => '200000.00',
                'orders_id' => 23,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'FGHG',
                'image' => NULL,
                'created_at' => '2020-04-17 12:26:52',
                'updated_at' => '2020-04-17 16:28:08',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            43 => 
            array (
                'id' => 43,
                'amount' => '30000.00',
                'orders_id' => 24,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'GHJH',
                'image' => NULL,
                'created_at' => '2020-04-17 12:29:12',
                'updated_at' => '2020-04-17 16:29:30',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            44 => 
            array (
                'id' => 44,
                'amount' => '6415.72',
                'orders_id' => 24,
                'bank_datas_id' => 1,
                'status' => 'aprobado',
                'ref' => 'OKO6',
                'image' => NULL,
                'created_at' => '2020-04-17 12:29:23',
                'updated_at' => '2020-04-17 16:29:50',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            45 => 
            array (
                'id' => 45,
                'amount' => '307889.98',
                'orders_id' => 25,
                'bank_datas_id' => 1,
                'status' => 'rechazado',
                'ref' => 'pp',
                'image' => NULL,
                'created_at' => '2020-04-17 14:06:14',
                'updated_at' => '2020-04-17 18:11:29',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
            46 => 
            array (
                'id' => 46,
                'amount' => '766200.45',
                'orders_id' => 26,
                'bank_datas_id' => 1,
                'status' => 'rechazado',
                'ref' => 'pp',
                'image' => NULL,
                'created_at' => '2020-04-17 14:12:35',
                'updated_at' => '2020-04-17 18:12:47',
                'other_amount' => '0.00',
                'coins_id' => 2,
                'description' => NULL,
            ),
        ));
        
        
    }
}