<?php

use Illuminate\Database\Seeder;

class SubCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sub_categories')->delete();
        
        \DB::table('sub_categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'DERIVADOS DE HARINA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 1,
                'c_elementvalue_id_n4' => 1005395,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'SALSAS PARA PASTAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 2,
                'c_elementvalue_id_n4' => 1005965,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'AFEITADA Y DEPILACION',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005666,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'CHOCOLATES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 4,
                'c_elementvalue_id_n4' => 1006079,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'BLANCOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 5,
                'c_elementvalue_id_n4' => 1005265,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'HORTALIZAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 6,
                'c_elementvalue_id_n4' => 1005258,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'CUIDADO BEBE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005679,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'PASTAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 7,
                'c_elementvalue_id_n4' => 1005911,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'EMBUTIDOS DE SALCHICHA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 8,
                'c_elementvalue_id_n4' => 1005550,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'GALLETAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 9,
                'c_elementvalue_id_n4' => 1006055,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ARROZ',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 10,
                'c_elementvalue_id_n4' => 1005578,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'CUIDADO COCINA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005798,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'DIETETICO Y NATURAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 9,
                'c_elementvalue_id_n4' => 1006039,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'JUGUETES MANUALES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 12,
                'c_elementvalue_id_n4' => 1006314,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'SALSA DE TOMATE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 13,
                'c_elementvalue_id_n4' => 1005943,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'PRODUCTOS CRUDOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 14,
                'c_elementvalue_id_n4' => 1005547,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'SOPAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 13,
                'c_elementvalue_id_n4' => 1005930,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'DETERGENTE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005835,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'LECHES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 7,
                'c_elementvalue_id_n4' => 1005880,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'ALIMENTOS/PERROS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 15,
                'c_elementvalue_id_n4' => 1005859,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'HARINAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 10,
                'c_elementvalue_id_n4' => 1005585,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'CUIDADO ROPA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005806,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ENLATADOS VEGETALES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 2,
                'c_elementvalue_id_n4' => 1006004,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'REFRESCOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006160,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ASEO BAÑO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005792,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'EMBUTIDOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 14,
                'c_elementvalue_id_n4' => 1005525,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'GRANOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 7,
                'c_elementvalue_id_n4' => 1005899,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'ENLATADOS CARNICOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 2,
                'c_elementvalue_id_n4' => 1005973,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'LIMPIADORES MULTIUSO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005764,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'NO REFRIGERADA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 17,
                'c_elementvalue_id_n4' => 1005432,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'VEGETALES CONGELADOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 18,
                'c_elementvalue_id_n4' => 1005488,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'GRASAS Y PREPARADOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 19,
                'c_elementvalue_id_n4' => 1005357,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'CUIDADO DEL CABELLO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005703,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'VERDE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 6,
                'c_elementvalue_id_n4' => 1005261,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'OTROS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 20,
                'c_elementvalue_id_n4' => 1005469,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'LIMPIADORES ESPECIALES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005838,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'CARNES PROCESADAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 18,
                'c_elementvalue_id_n4' => 1005484,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'AMARILLOS MADURADOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 5,
                'c_elementvalue_id_n4' => 1005300,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'PASAPALOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006148,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'SAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 10,
                'c_elementvalue_id_n4' => 1005597,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'LECHE UHT',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 19,
                'c_elementvalue_id_n4' => 1005340,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'PRODUCTOS PARA UNTAR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 2,
                'c_elementvalue_id_n4' => 1005957,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'AGUA MINERAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006130,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'PAPELES/CUID.HOGAR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005771,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'SALSAS EN GENERAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 13,
                'c_elementvalue_id_n4' => 1005945,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'PAÑALES DESECHABLES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005642,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'CREMAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 21,
                'c_elementvalue_id_n4' => 1005328,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'DESECHABLES Y PLASTICO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005820,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'WHISKY',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006199,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'RES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 20,
                'c_elementvalue_id_n4' => 1005457,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'AZUCAR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 10,
                'c_elementvalue_id_n4' => 1005574,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'VINOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006177,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'BEBIDAS ENERGETICA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006137,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'CUIDADO BUCAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005693,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'PAPAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 18,
                'c_elementvalue_id_n4' => 1005502,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'DESODORANTE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005728,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'JABON TOCADOR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005614,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'GRASAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 7,
                'c_elementvalue_id_n4' => 1005895,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'CAFE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 10,
                'c_elementvalue_id_n4' => 1005569,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'CERDO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 20,
                'c_elementvalue_id_n4' => 1005464,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'MODIFICADORES BEBIDAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 9,
                'c_elementvalue_id_n4' => 1006072,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'ACCESORIOS DE PLAYA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 23,
                'c_elementvalue_id_n4' => 1006264,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'RON',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006232,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'PROTECCION HOGAR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005783,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'JUGOS NO REFRIGERADOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006140,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'CAMPING',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 23,
                'c_elementvalue_id_n4' => 1006273,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'SANGRIA Y LAMBRUZCO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006172,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'ENLATADOS DEL MAR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 2,
                'c_elementvalue_id_n4' => 1005978,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'CEREALES LISTOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 9,
                'c_elementvalue_id_n4' => 1006032,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'PROTECCION SANITARIA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005649,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'ACEITES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 7,
                'c_elementvalue_id_n4' => 1005888,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'GOLOSINAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 4,
                'c_elementvalue_id_n4' => 1006084,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'OTROS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 24,
                'c_elementvalue_id_n4' => 1005481,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'MAYONESA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 13,
                'c_elementvalue_id_n4' => 1005936,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'VERDE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 25,
                'c_elementvalue_id_n4' => 1005423,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'YOGURES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 19,
                'c_elementvalue_id_n4' => 1005362,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'POLLO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 24,
                'c_elementvalue_id_n4' => 1005472,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'EMBUTIDOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 8,
                'c_elementvalue_id_n4' => 1005555,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'GINEBRA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006220,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'HORTALIZAS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 25,
                'c_elementvalue_id_n4' => 1005420,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'VINAGRE',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 7,
                'c_elementvalue_id_n4' => 1005919,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'PAPELES/CUID.PERSONAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 11,
                'c_elementvalue_id_n4' => 1005777,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'TE NO REFRIGERADO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006144,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'BEBIDAS EN POLVO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 16,
                'c_elementvalue_id_n4' => 1006134,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'HUEVOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 19,
                'c_elementvalue_id_n4' => 1005368,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'CONDIMENTOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 13,
                'c_elementvalue_id_n4' => 1005924,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'JAMON Y PECHUGA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 14,
                'c_elementvalue_id_n4' => 1005518,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'HIELO',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 18,
                'c_elementvalue_id_n4' => 1005515,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'INFUSIONES',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 2,
                'c_elementvalue_id_n4' => 1006026,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'JUGUETES ELECTRICOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 12,
                'c_elementvalue_id_n4' => 1006312,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'CUIDADO FACIAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005715,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'VINOS DE COCINA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006189,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'CUIDADO CORPORAL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005658,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'AMARILLOS SEMI MADURADOS',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 5,
                'c_elementvalue_id_n4' => 1005285,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'ALIMENTOS INFANTIL',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 9,
                'c_elementvalue_id_n4' => 1006049,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'CERVEZA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006216,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'VODKA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 22,
                'c_elementvalue_id_n4' => 1006196,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'LINEA SOLAR',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 3,
                'c_elementvalue_id_n4' => 1005621,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'ILUMINACION',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 26,
                'c_elementvalue_id_n4' => 1006474,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'MOSTAZA',
                'description' => NULL,
                'image' => NULL,
                'status' => 'A',
                'categories_id' => 13,
                'c_elementvalue_id_n4' => 1005941,
                'created_at' => NULL,
                'updated_at' => NULL,
                'position' => NULL,
            ),
        ));
        
        
    }
}